.github/workflows/flake-updater.yml
.github/workflows/nix.yml

Setting up workflow, nix flake integ
flake update pr on weekly basis

fix gh action for flake check and update

---

host/common/services/default.nix
host/common/services/mysql.nix
modules/nixos/programs/intellij.nix

Fix jdk for use with intellij for debug.
Setup mysql service, running background as daemon

fix intellij build debug options

---

home/programs/gnome.nix

Change keybinding for lockscreen to common Super+L

---

flake.lock
hosts/system/zsh.nix

Vil bare ha alias for git push

Add git push git alias

---

home/users/jhhhnikt/default.nix

Oppdatert jhhhnikt default.nix

---

home/users/jhhhnikt/default.nix
hosts/users/jhhhnikt/default.nix

Lagt til flere bruker-apper, overstyrer favoritter i gnome, xrandr kommando.

Diverse jhhhnikt

---

home/users/sigubrat/default.nix

Takk til @neethan for fiksen
https://github.com/HNIKT-Tjenesteutvikling-Systemutvikling/NixHNIKT/assets/47779602/98014347-defc-4673-a142-aa4446dbd8b1

Fix git not working in vscode terminal

---

home/programs/browser/firefox.nix

endret browser til firefox dev

intervbs Updated system and home-manager for generation 65

---

home/users/intervbs/default.nix

intervbs Updated system and home-manager for generation 64

---

home/users/default.nix

Deaktiverer citrix for profilen min

Deaktiver citrix fordi den hverken brukes eller funker lengre

---

flake.lock

Automatic flake update on 2025-01-26

Auto update 2025-01-26

---

home/users/ievensen/default.nix

headsetcontrol for arctis headsets

added headsetcontrol pkg

---

flake.lock

Automatic flake update on 2025-02-09

Auto update 2025-02-09

---

flake.lock

Automatic flake update on 2025-02-16

Auto update 2025-02-16

---

flake.lock

Automatic flake update on 2025-02-23

Auto update 2025-02-23

---

flake.lock

Automatic flake update on 2025-03-02

Auto update 2025-03-02

---

flake.lock

Automatic flake update on 2025-03-14

Auto update 2025-03-14

---

flake.lock

Automatic flake update on 2025-03-17

Auto update 2025-03-17

---

flake.lock

Automatic flake update on 2025-03-31

Auto update 2025-03-31

---

flake.lock

Automatic flake update on 2025-04-07

Auto update 2025-04-07

---

flake.lock

Automatic flake update on 2025-04-14

Auto update 2025-04-14

---

flake.lock

Automatic flake update on 2025-04-21

Auto update 2025-04-21

---

system/programs/cachix/default.nix
system/programs/cachix/iog.nix

Adds iog cachix for haskell

---

flake.lock

Automatic flake update on 2025-04-28

Auto update 2025-04-28

---

modules/profiles/sigubrat/default.nix
system/programs/fish.nix

* Legger til RIKTIGE alias 
* Legger til horizon til min config

Fikser fiksen og tvinger Torkil til aa bruke riktige alias

---

flake.lock

Automatic flake update on 2025-05-12

Auto update 2025-05-12

---

flake.lock

Automatic flake update on 2025-05-13

Auto update 2025-05-13

---

flake.lock

Automatic flake update on 2025-05-19

Auto update 2025-05-19

---

flake.lock

Automatic flake update on 2025-05-26

Auto update 2025-05-26

---

flake.lock

Automatic flake update on 2025-06-02

Auto update 2025-06-02

---

.github/workflows/flake-check.yml
modules/programs/vscode.nix

Rebuild VsCode to have a default config for development

VsCode default options

---

flake.lock

Automatic flake update on 2025-06-23

Auto update 2025-06-23

---

flake.lock

Automatic flake update on 2025-07-07

Auto update 2025-07-07
